"""
Django settings for cctvSystem project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os



os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'cctvSystem.settings')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent




# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-++=jvq2f4foa*#z60md5)45&&w8ev(cw***0xaic3i0o3@hrkt'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False
ALLOWED_HOSTS = ['127.0.0.1','192.168.101.101','131.100.37.184','192.168.102.247','200.125.163.182','www.surveillance.crc.com']

CSRF_TRUSTED_ORIGINS = [
    "http://www.surveillance.crc.com"   
                       ]


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles', 
    'cctv',    
        ]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'cctv.middleware.COOPHeaderMiddleware',
    ]

ROOT_URLCONF = 'cctvSystem.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
           
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cctvSystem.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'crcCCTV_db.db',
    }
}

#DATABASES = {
#   "default": {
#    "ENGINE": "django.db.backends.postgresql",
#   "NAME": "crc_db",
#    "USER": "mlestrada",
#   "PASSWORD": "Remate123*+",
#   "HOST": "localhost",
#    "PORT": "5432",
#  }
#}

#Email settings
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
#EMAIL_HOST = "smtp.gmail.com"
EMAIL_HOST = "mail.clubroyalcaribbean.net"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
#EMAIL_HOST_USER = "maiselluis@gmail.com"
EMAIL_HOST_USER = "cctvsupport@clubroyalcaribbean.net"
EMAIL_HOST_PASSWORD = "597868@Lcr"
#EMAIL_HOST_PASSWORD = "ywdy mksa arpm qhhx"



# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

FORMAT_MODULE_PATH = [
    "cctv.formats",
]

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Caracas'

USE_I18N = True

USE_L10N = False
USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT=os.path.join(BASE_DIR,'static')

STATIC_FILE_DIR=os.path.join(BASE_DIR,'static')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR,'media')


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
#SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin"


LOGIN_REDIRECT_URL = '/' 
LOGOUT_REDIRECT_URL = '/accounts/login/'
SESSION_COOKIE_AGE = 1209600  # Duración estándar de la sesión (2 semanas)
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # No expirar al cerrar el navegador (a menos que se configure explícitamente)

JAZZMIN_UI_TWEAKS = {
    "theme": "cosmo",  # Tema de Bootstrap
    "dark_mode_theme": "darkly",  # Tema para modo oscuro
   
}
JAZZMIN_SETTINGS = {
    "site_brand": "Administration Panel",  # Nombre que aparece en la barra lateral
    "site_logo": 'lib/images/LOGO.ico',  # Ruta del logo dentro de static/
    "login_logo": "lib/images/LOGO.ico",  # Logo en la pantalla de login
    "login_logo_dark": "lib/images/LOGO.ico",  # Opcional, para modo oscuro
     "show_ui_builder": False,  # Oculta el botón de UI Builder

    "icons": {
        "auth.user": "fas fa-user-shield",        # Icono de usuario
        "cctv.userprofile": "fas fa-user-check",       # Icono de grupos
        "cctv.notification": "fas fa-bell"  # Icono de base de datos
    
            },
    "custom_links": {
        "cctv": [
            {
                "name": "Last user login",
                "url": "user_last_login",  # Nombre de la URL definida en urls.py
                "icon": "fas fa-clock",    # Puedes cambiar el icono si quieres
                "permissions": ["auth.view_user"],  # Asegura que solo los que pueden ver usuarios lo vean
            }
        ]
    }
   
}