# Generated by Django 5.1.4 on 2024-12-17 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='sex',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='cctv.sex', verbose_name='sex'),
        ),
        migrations.AlterModelTable(
            name='race',
            table='tb_race',
        ),
    ]
