# Generated by Django 5.1.4 on 2024-12-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0002_alter_blacklist_sex_alter_race_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='photo',
            field=models.ImageField(default='images/noimage.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='reportvideo',
            name='caption',
            field=models.CharField(max_length=250),
        ),
    ]
