# Generated by Django 5.1.4 on 2024-12-21 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0002_alter_blacklist_sex_alter_race_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cash_desk_transaction',
            options={'get_latest_by': '-transactions', 'ordering': ['-transactions', 'date', 'time', 'location'], 'verbose_name': 'Cash Desk Tansactions', 'verbose_name_plural': 'Cash Desk Transactions'},
        ),
        migrations.AddField(
            model_name='customer',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk_location_customer', to='cctv.location', verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='photo',
            field=models.ImageField(default='images/noimage.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='reportvideo',
            name='caption',
            field=models.CharField(max_length=250),
        ),
    ]
