# Generated by Django 5.1.4 on 2024-12-21 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0003_alter_customer_photo_alter_reportvideo_caption'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cash_desk_transaction',
            options={'get_latest_by': '-transactions', 'ordering': ['-transactions', 'date', 'time', 'location'], 'verbose_name': 'Cash Desk Tansactions', 'verbose_name_plural': 'Cash Desk Transactions'},
        ),
        migrations.AddField(
            model_name='customer',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk_location_customer', to='cctv.location', verbose_name='Branch'),
        ),
    ]
