# Generated by Django 5.1.4 on 2024-12-23 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0003_alter_cash_desk_transaction_options_and_more'),
        ('cctv', '0004_alter_cash_desk_transaction_options_and_more'),
    ]

    operations = [
    ]
