# Generated by Django 5.1.4 on 2024-12-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0005_merge_20241223_1108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exceptiontype',
            options={'get_latest_by': 'id', 'ordering': ['id'], 'verbose_name': 'Daily Exeption Type', 'verbose_name_plural': 'Daily Exeption Types'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'get_latest_by': '-id', 'verbose_name': 'Staff', 'verbose_name_plural': 'Staffs'},
        ),
        migrations.AlterUniqueTogether(
            name='dailyshift',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='report',
            name='action_token',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Action Taken'),
        ),
    ]
