# Generated by Django 5.1.4 on 2024-12-28 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0006_alter_exceptiontype_options_alter_staff_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_nro',
            field=models.IntegerField(default=1, verbose_name='Report #'),
            preserve_default=False,
        ),
    ]
