# Generated by Django 5.1.4 on 2024-12-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0007_report_report_nro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counterfait',
            name='report',
        ),
        migrations.AddField(
            model_name='counterfait',
            name='report_nro',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
