# Generated by Django 5.1.4 on 2024-12-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0008_remove_counterfait_report_counterfait_report_nro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterfait',
            name='report_nro',
            field=models.IntegerField(verbose_name='Report #'),
        ),
    ]
