# Generated by Django 5.1.4 on 2025-01-03 22:04

import cctv.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0009_alter_counterfait_report_nro'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterfait',
            name='area_cashier',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk_counterfeit_area_cashier', to='cctv.areacashier', verbose_name='Area Cashier'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportvideo',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to=cctv.models.video_upload_to),
        ),
    ]
