# Generated by Django 5.1.4 on 2025-01-03 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0010_counterfait_area_cashier_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counterfait',
            options={'get_latest_by': '-id', 'ordering': ['id', 'date', 'location'], 'verbose_name': 'Counterfait', 'verbose_name_plural': 'Counterfait'},
        ),
        migrations.RemoveField(
            model_name='counterfait',
            name='time',
        ),
    ]
