# Generated by Django 5.1.4 on 2025-01-04 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0011_alter_counterfait_options_remove_counterfait_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['-id'], 'verbose_name': 'Shift', 'verbose_name_plural': 'Shifts'},
        ),
        migrations.AddField(
            model_name='report',
            name='other1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk_other1', to='cctv.staff', verbose_name='Other 1'),
        ),
    ]
