# Generated by Django 5.1.4 on 2025-01-04 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0012_alter_shift_options_report_other1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['customer'], 'verbose_name': 'Customers', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AddField(
            model_name='report',
            name='attendant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk_attendant', to='cctv.staff', verbose_name='Attendant'),
        ),
        migrations.AddField(
            model_name='report',
            name='cashier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk_cashier', to='cctv.staff', verbose_name='Cashier'),
        ),
        migrations.AddField(
            model_name='report',
            name='duty_manager1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk_duty_manager1', to='cctv.staff', verbose_name='Duty Manager 1'),
        ),
        migrations.AddField(
            model_name='report',
            name='senior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk_senior', to='cctv.staff', verbose_name='Senior'),
        ),
        migrations.AddField(
            model_name='report',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk_supervisor_report', to='cctv.staff', verbose_name='Supervisor'),
        ),
    ]
