# Generated by Django 5.1.4 on 2025-01-09 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0013_alter_customer_options_report_attendant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='attendant',
        ),
        migrations.RemoveField(
            model_name='report',
            name='cashier',
        ),
        migrations.RemoveField(
            model_name='report',
            name='duty_manager1',
        ),
        migrations.RemoveField(
            model_name='report',
            name='other1',
        ),
        migrations.RemoveField(
            model_name='report',
            name='senior',
        ),
        migrations.RemoveField(
            model_name='report',
            name='supervisor',
        ),
    ]
