# Generated by Django 5.1.4 on 2025-01-12 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0014_remove_report_attendant_remove_report_cashier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash_desk_transaction',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_customer', to='cctv.customer', verbose_name='Customer'),
        ),
    ]
