# Generated by Django 5.1.4 on 2025-01-12 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0015_alter_cash_desk_transaction_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_area', to='cctv.area', verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='report',
            name='cctv_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_cctv_Staff', to='cctv.staff', verbose_name='Cctc Id'),
        ),
        migrations.AlterField(
            model_name='report',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_customer_report', to='cctv.customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='report',
            name='dealer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_dealer', to='cctv.staff', verbose_name='Inspector'),
        ),
        migrations.AlterField(
            model_name='report',
            name='duty_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_duty_manager', to='cctv.staff', verbose_name='Duty Manager'),
        ),
        migrations.AlterField(
            model_name='report',
            name='inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_inspector', to='cctv.staff', verbose_name='Inspector'),
        ),
        migrations.AlterField(
            model_name='report',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_location_report', to='cctv.location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='report',
            name='origination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_origination', to='cctv.reportorigination', verbose_name='Report Origination'),
        ),
        migrations.AlterField(
            model_name='report',
            name='other',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_other', to='cctv.staff', verbose_name='Other'),
        ),
        migrations.AlterField(
            model_name='report',
            name='pittboss',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_pitboss', to='cctv.staff', verbose_name='Pit Boss'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_report_title_report', to='cctv.reporttitle', verbose_name='Report Title'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_report_type', to='cctv.reporttype', verbose_name='Report Type'),
        ),
    ]
