# Generated by Django 5.1.4 on 2025-01-12 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0016_alter_report_area_alter_report_cctv_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyshift',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_location_daily', to='cctv.location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='dailyshift',
            name='officer1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_officer1', to='cctv.staff', verbose_name='officer1'),
        ),
        migrations.AlterField(
            model_name='dailyshift',
            name='officer2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_officer2', to='cctv.staff', verbose_name='officer2'),
        ),
        migrations.AlterField(
            model_name='dailyshift',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_shift', to='cctv.shift', verbose_name='Shift'),
        ),
        migrations.AlterField(
            model_name='dailyshift',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_supervisor', to='cctv.staff', verbose_name='supervisor'),
        ),
    ]
