# Generated by Django 5.1.4 on 2025-01-12 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0017_alter_dailyshift_location_alter_dailyshift_officer1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash_desk_error',
            name='area_cashier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='fk_area_cashier_cderror', to='cctv.areacashier', verbose_name='Area Cashier'),
        ),
        migrations.AlterField(
            model_name='cash_desk_error',
            name='cashier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='fk_cashier_cash_desk_error', to='cctv.staff', verbose_name='Cashier'),
        ),
        migrations.AlterField(
            model_name='cash_desk_error',
            name='duty_manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='fk_duty_manager_dalily_cash_desk_error', to='cctv.staff', verbose_name='Duty Manager'),
        ),
        migrations.AlterField(
            model_name='cash_desk_error',
            name='error_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='error_type_cash_desk_error', to='cctv.cderrortype', verbose_name='CD Error Type'),
        ),
        migrations.AlterField(
            model_name='cash_desk_error',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='fk_branch_cd_error', to='cctv.location', verbose_name='Branh'),
        ),
        migrations.AlterField(
            model_name='cash_desk_error',
            name='supervisor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='fk_supervisor_cash_desk_error', to='cctv.staff', verbose_name='Supervisor/Senior'),
        ),
        migrations.AlterField(
            model_name='cash_desk_transaction',
            name='account_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_account_type', to='cctv.accounttype', verbose_name='Account Type'),
        ),
        migrations.AlterField(
            model_name='cash_desk_transaction',
            name='area_cashier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_area_cashier_transaction', to='cctv.areacashier', verbose_name='Area Cashier'),
        ),
        migrations.AlterField(
            model_name='cash_desk_transaction',
            name='autorized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_autorized', to='cctv.staff', verbose_name='Autorized by'),
        ),
        migrations.AlterField(
            model_name='cash_desk_transaction',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_employee', to='cctv.staff', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='cash_desk_transaction',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_location_cash_transaction', to='cctv.location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='cash_desk_transaction',
            name='token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_token', to='cctv.token', verbose_name='Token'),
        ),
    ]
