# Generated by Django 5.1.4 on 2025-01-12 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0018_alter_cash_desk_error_area_cashier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poker_payout',
            name='combination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='fk_poquer_combination', to='cctv.pokercombination', verbose_name='Combination'),
        ),
        migrations.AlterField(
            model_name='poker_payout',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_poker_payout', to='cctv.customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='poker_payout',
            name='dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_dealer_poker', to='cctv.staff', verbose_name='Dealer'),
        ),
        migrations.AlterField(
            model_name='poker_payout',
            name='inspector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_inspector_poker', to='cctv.staff', verbose_name='Inspector'),
        ),
        migrations.AlterField(
            model_name='poker_payout',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='fk_poker_error', to='cctv.location', verbose_name='Branh'),
        ),
        migrations.AlterField(
            model_name='poker_payout',
            name='pitboss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_pitboos_poker', to='cctv.staff', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='poker_payout',
            name='table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='fk_poker_table', to='cctv.pokertable', verbose_name='Poker Table'),
        ),
    ]
