# Generated by Django 5.1.4 on 2025-01-12 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0019_alter_poker_payout_combination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterfait',
            name='area_cashier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_counterfeit_area_cashier', to='cctv.areacashier', verbose_name='Area Cashier'),
        ),
        migrations.AlterField(
            model_name='counterfait',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_location_counterfait', to='cctv.location', verbose_name='Location'),
        ),
    ]
