# Generated by Django 5.1.4 on 2025-01-12 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0020_alter_counterfait_area_cashier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyexeption',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_daily_exception', to='cctv.staff', verbose_name='Employeee'),
        ),
        migrations.AlterField(
            model_name='dailyexeption',
            name='exception_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_daily_exception', to='cctv.exceptiontype', verbose_name='Exeption Type'),
        ),
        migrations.AlterField(
            model_name='dailyexeption',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_location_daily_exception', to='cctv.location', verbose_name='Location'),
        ),
    ]
