# Generated by Django 5.1.4 on 2025-01-12 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0021_alter_dailyexeption_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='blacklistby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blacklistby', to='cctv.staff', verbose_name='blacklistby'),
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='duration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cctv.duration', verbose_name='duration'),
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cctv.location', verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cctv.race', verbose_name='race'),
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cctv.reason', verbose_name='reason'),
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='sex',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='cctv.sex', verbose_name='sex'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='fk_location_customer', to='cctv.location', verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='main',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_location_main', to='cctv.location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='position_department', to='cctv.department'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cctv.location', verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='position_position', to='cctv.position'),
        ),
    ]
