# Generated by Django 5.1.4 on 2025-01-24 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0022_alter_blacklist_blacklistby_alter_blacklist_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot_Machine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id machine')),
                ('name', models.TextField(verbose_name='Machine No.')),
            ],
            options={
                'verbose_name': 'Slot Machine',
                'verbose_name_plural': 'Slot Machine',
                'db_table': 'tb_slot_machine',
                'ordering': ['id'],
                'get_latest_by': '-id',
            },
        ),
        migrations.AddField(
            model_name='cash_desk_transaction',
            name='machine_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_machine_transaction', to='cctv.slot_machine', verbose_name='Machine Slot'),
        ),
    ]
