# Generated by Django 5.1.4 on 2025-01-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0023_slot_machine_cash_desk_transaction_machine_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash_desk_error',
            name='found',
            field=models.BooleanField(default=False),
        ),
    ]
