# Generated by Django 5.1.4 on 2025-01-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0024_cash_desk_error_found'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash_desk_transaction',
            name='detail',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Detail'),
        ),
    ]
