# Generated by Django 5.1.4 on 2025-01-27 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0025_cash_desk_transaction_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterfait',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_customer_counterfeit', to='cctv.customer', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='counterfait',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_employee_counterfeit', to='cctv.staff', verbose_name='Employee'),
        ),
    ]
