# Generated by Django 5.1.4 on 2025-02-17 16:48

import cctv.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0027_alter_counterfait_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplies',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='Nro.')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('request', models.CharField(choices=[('supplies', 'SUPPLIES'), ('equipemnt', 'EQUIPMENT'), ('service', 'SERVICE'), ('other', 'OTHER')], default='supplies', max_length=20)),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='Detail')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=cctv.models.supplies_upload_to)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_staff_approved', to='cctv.staff', verbose_name='Approved by')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_supplies_branch', to='cctv.location', verbose_name='Branch')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_supplies', to='cctv.department', verbose_name='Department')),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_staff_supplies', to='cctv.staff', verbose_name='Prepared by')),
            ],
            options={
                'verbose_name': 'Supplies',
                'verbose_name_plural': 'Supplies',
                'db_table': 'tb_supplies',
                'ordering': ['-id'],
                'get_latest_by': '-id',
            },
        ),
    ]
