# Generated by Django 5.1.4 on 2025-02-17 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0028_supplies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplies',
            name='request',
        ),
        migrations.AddField(
            model_name='supplies',
            name='request_for',
            field=models.CharField(choices=[('supplies', 'SUPPLIES'), ('equipment', 'EQUIPMENT'), ('service', 'SERVICE'), ('other', 'OTHER')], default='supplies', max_length=20),
        ),
    ]
