# Generated by Django 5.1.4 on 2025-03-19 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0029_remove_supplies_request_supplies_request_for'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyshift',
            name='officer1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_officer1', to='cctv.staff', verbose_name='officer1'),
        ),
        migrations.AlterField(
            model_name='dailyshift',
            name='officer2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_officer2', to='cctv.staff', verbose_name='officer2'),
        ),
        migrations.AlterField(
            model_name='dailyshift',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fk_supervisor', to='cctv.staff', verbose_name='supervisor'),
        ),
        migrations.AlterField(
            model_name='slot_machine',
            name='name',
            field=models.IntegerField(verbose_name='Machine No.'),
        ),
       
    ]
