# Generated by Django 5.1.4 on 2025-03-19 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0030_alter_dailyshift_officer1_alter_dailyshift_officer2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_location', to='cctv.location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_notification',
                'unique_together': {('location', 'user')},
            },
        ),
    ]
