# Generated by Django 5.1.4 on 2025-03-20 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0032_alter_notification_location_alter_notification_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-location']},
        ),
        migrations.AddField(
            model_name='cash_desk_error',
            name='report',
            field=models.IntegerField(blank=True, null=True, verbose_name='Report Nr.'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='cctv.location', verbose_name='Branch'),
        ),
    ]
