# Generated by Django 5.1.4 on 2025-04-02 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0033_alter_notification_options_cash_desk_error_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyexeption',
            name='daily_from',
            field=models.TimeField(blank=True, null=True, verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='dailyexeption',
            name='daily_to',
            field=models.TimeField(blank=True, null=True, verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='dailyexeption',
            name='new_shift',
            field=models.TimeField(blank=True, null=True, verbose_name='New Shift'),
        ),
        migrations.AlterField(
            model_name='dailyexeption',
            name='old_shift',
            field=models.TimeField(blank=True, null=True, verbose_name='Old Shift'),
        ),
    ]
