# Generated by Django 5.1.4 on 2025-05-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0034_alter_dailyexeption_daily_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklist',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
